var data = [4, 8, 15, 16, 23, 42, 100, 150, 30]

var hScale = d3.scale.linear()
  .domain([0, d3.max(data)])
  .range([0, 420])

var vScale = d3.scale.ordinal()
  .domain(data)
  .rangeBands([0, 120])

var chart = d3.select("body").append("svg")
  .attr("class", "chart")
  .attr("width", 420)
  .attr("height", 20 * data.length)
  //.append("g")
  //  .attr("transform", "translate(10,15)")

chart.selectAll("rect")
  .data(data)
  .enter().append("rect")
  .attr("y", vScale) 
  .attr("width", hScale)
  .attr("height", vScale.rangeBand())

chart.selectAll("text")
  .data(data)
  .enter().append("text")
  .attr("x", hScale)
  .attr("y", function(d) { return vScale(d) + vScale.rangeBand() / 2 })
  .attr("dx", -3)
  .attr("dy", ".35em")
  .attr("text-anchor", "end")
  .attr("fill", "white")
  .attr("font-size", 10)
  .text(String)

//console.log(hScale.ticks(10))
//chart.selectAll("line")
//  .data(hScale.ticks(10))
//  .enter().append("line")
//  .attr("x1", hScale)
//  .attr("x2", hScale)
//  .attr("y1", 0)
//  .attr("y2", 120)
//  .style("stroke", "#ccc")
